# Generated by Django 2.2.16 on 2021-12-01 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211201_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='code_confirmation',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
