# Generated by Django 2.2.16 on 2021-12-04 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20211204_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('useerwerwer', 'useerwerwer'), ('moderator', 'moderator'), ('admin', 'admin')], default='useerwerwer', max_length=100, null=True),
        ),
    ]
