# Generated by Django 2.2.16 on 2021-12-06 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20211206_0957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='rewiev',
            new_name='review',
        ),
    ]
